@startuml
start
while (Expected ""<sequence_id>""?) is (yes)
fork
if (Has ""<payload>""?) then (yes)
:Process ""<payload>"";
endif
fork again
if (Has ""<retransmit_id>""?) then (yes)
:Resend requested record;
endif
end fork
:Clear outgoing buffer where\n""<sequence_id> < <expected_id>"";
if (Unprocessed records?) then (no)
stop
endif
endwhile (no)
:Add to unprocessed records;
stop
@enduml
