@startuml

participant Controller as C
participant Agent as A

C ->> A : Operate Request (command)
activate A

A -> A : Create instance of Request Object

A --> C : [ send_resp == true ]\nOperate Response (req_object_path)

A -> A : Operation started
deactivate A

note over C : The Controller can use\nthe Request Object Path\nin order to retrieve\noperation-related Parameters\nuntil the operation completes.

A -> A : Operation completed and returned (success or failure)
A -> A : Remove Request Object
activate A

A -> C : [ Controller has subscribed to this operation ]\nNotify Request ("OperationComplete", req_output_args)
deactivate A

@enduml
