@startuml

participant Controller as C
participant Agent as A

C ->> A : Operate Request (command)
activate A

A -> A : Perform operation

A --> C : [ send_resp == true ]\nOperate Response (operation_result)
deactivate A

@enduml
